### PR TITLE
fixed: taint labels not being applied to `Dot` offsets

### LINKED ISSUE #6355: Labels not being applied correctly to taint rule
**Describe the bug**
We are producing a finding when we shouldn't be, because a label being used as a "requires" should be preventing the finding, but it is not.

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev: https://semgrep.dev/playground/s/JPRQ

**Expected behavior**
There should be no finding, because the `USERINPUT` label is not satisfied by the source.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
Correctness.

### PR DESCRIPTION
**Pull request by brandonspark**
## What:
Currently, we are producing findings that should be made impossible due to taint labels. These specifically only occur in the case of them resulting from a `Dot` / `DotAccess`.

## Why:
This is a regular bug that should be fixed. In particular, it was causing erroneous findings on these cases:
https://semgrep.dev/playground/s/JPRQ
https://semgrep.dev/playground/s/RW7N

## How:
We weren't filtering for labels when producing taint from a tainted token, which the `Dot` case was degenerating to. I just added in a filtering step.

Fixes #6355 

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

File: semgrep-core/src/tainting/Dataflow_tainting.ml [hunk 1]
```diff
@@ -409,6 +409,11 @@ let check_tainted_tok env tok =
   | _ :: _ -> (Taints.empty, env.lval_env)
   | [] ->
       let taints = source_pms |> taints_of_matches in
+      (* Empty because we have no base, but we want to filter the taints we got from
```
Comment (emjin) [inline semgrep-core/src/tainting/Dataflow_tainting.ml]: Totally fair if this comment just needs a lot of context, but from this snippet it's hard to understand. Main sources of confusion are probably "because we have no base"

**Review by emjin — COMMENTED** [review]
Can you add a test case?

File: semgrep-core/src/tainting/Dataflow_tainting.ml (hunk 1 above)
Comment (emjin) [reply semgrep-core/src/tainting/Dataflow_tainting.ml]: > a tainted token, which the Dot case was degenerating to

This from the PR is helpful, could use it in the code

File: changelog.d/gh-6355.fixed [hunk 2]
```diff
@@ -0,0 +1 @@
+Taint: Fixed a bug where taint labels were not being correctly applied to findings resulting from dot accesses. For instance, a taint pattern with a `requires` involving `x.y` might ignore the `requires` if the `y` produces a match.
```
Comment (IagoAbal) [inline changelog.d/gh-6355.fixed]: Even if just to make the review easier, we should hard wrap these files at 80 chars. It's painful having to scroll horizontally so much. Otherwise I need to open the file "raw" so that I can get soft wrapping by the browser.

**Comment by IagoAbal** [comment]
We need to add at least one regression test to this PR, to make sure we detect the problem the next time.

File: changelog.d/gh-6355.fixed (hunk 2 above)
Comment (IagoAbal) [reply changelog.d/gh-6355.fixed]: > Taint: Fixed a bug where taint labels were not being correctly applied to findings resulting from dot accesses. For instance, a taint pattern with a `requires` involving `x.y` might ignore the `requires` if the `y` produces a match.

Maybe

> taint-mode: Fixed a bug in the experimental taint-labels feature that caused labels to be incorrectly applied to dot accesses. For instance, if a `pattern-source` that requires label `A` and adds label `B` matches a dot-access expression like `x.a`, the field `a` will get the label `B` even if it does not carry label `A` as required.

? 

cc @adamkvitek may give a more objective opinion.

**Comment by IagoAbal** [comment]
Also, what GitHub issue is this fixing? I saw a bug report filed by yourself that seems to be fixed by this PR.

**Comment by enncoded** [comment]
> Also, what GitHub issue is this fixing? I saw a bug report filed by yourself that seems to be fixed by this PR.

@IagoAbal It's fixing https://github.com/returntocorp/semgrep/issues/6355, which I reported in the PA channel in slack, but Brandon filed a GH issue for it before I finished doing so. I left some details about its importance to me in the Linear issue.

File: semgrep-core/tests/tainting_rules/go/token_labels.yaml [hunk 3]
```diff
@@ -0,0 +1,16 @@
+rules:
+  - id: go-token-labels
+    message: A taint label did not prevent the match coming from a tainted token!
```
Comment (emjin) [inline semgrep-core/tests/tainting_rules/go/token_labels.yaml:3]: I got confused so maybe specify that the point is this is an unsatisfiable label and we're testing that the label works. Having the issue helps though

**Review by emjin — APPROVED** [review]
I'm not personally a huge fan of the fact that we have to copy this filtering step in four places, but you're just following previous convention so I'm fine with this PR.

File: semgrep-core/tests/tainting_rules/go/token_labels.go [hunk 4]
```diff
@@ -0,0 +1,8 @@
+// See https://github.com/returntocorp/semgrep/issues/6355 if this breaks.
```
Comment (IagoAbal) [inline semgrep-core/tests/tainting_rules/go/token_labels.go:1]: The `tainting_rules` folder comes from a time when you couldn't pass taint rules to `-rules`, you had to use a different switch `-tainting_rules` or something. Nowadays I just add these tests in `tests/rules` but prefixed with `taint_`. I'll see if I can move all tests soon.

**Review by IagoAbal — APPROVED** [review]
Nice! Let's merge it. In #6279 I actually removed `check_tainted_tok` anyways, but in the meantime we fix the bug and it's also useful to get the new test case.
