### PR TITLE
Match "OtherAttribute" attributes in any order

### LINKED ISSUE #1406: Matching Python annotations containing "." characters
**Describe the bug**
When trying to match an annotation on a python method that contains a "." character the match fails

**To Reproduce**

In the following code snippet:

```
@ns.route('/store/<int:checklist_type>/<int:maturity>')
@api.response(404, 'Validation error', message)
class QuestionSprintStoreCollection(Resource):

    @api.expect(authorization, store_list_items)
    @api.marshal_with(message, 'Success')
    @api.response(400, 'No results found', message)
    def put(self, checklist_type, maturity):
        """
        Store list of question sprint items.
```

This pattern will match the class annotator:

```
- pattern: |
      @ns.route($ROUTE)
      class $C(...):
```

but a similar pattern to match the class annotator "@api.response" fails:

```
- pattern: |
        @api.response(...)
        def $METH(...):
          ...
```

If I remove the . in the api.response string I can write a match pattern that works.

**Expected behavior**
Pattern should match the annotation

**Environment**
docker and semgrep.live

### PR DESCRIPTION
**Pull request by nbrahms**
We already have code to match keyword and named attributes in any order
in an attribute list, and to match with "less is ok" functionality.

This commit extends that to work with "OtherAttribute" AST nodes as
well. Note that it is not fully implemented here, as I took a shortcut
that would leave this pattern:

```python
@x("a")
@x("a")
def foo:
  ...
```

still matching this code:

```python
@x("a")
def foo:
  pass
```

I'm leaving this as a TODO for now.

Fixes #1406.

### CODE REVIEW

File: semgrep-core/matching/Generic_vs_generic.ml [hunk 1]
```diff
@@ -1298,13 +1298,25 @@ and m_list__m_attribute (xsa: A.attribute list) (xsb: A.attribute list) =
       with Not_found -> fail ()
       )
   (*e: [[Generic_vs_generic.m_list__m_attribute]] [[NamedAttr]] pattern case *)
-  (* the general case *)
```
Comment (nbrahms) [inline semgrep-core/matching/Generic_vs_generic.ml]: Note that "the general case" is actually just the specific "OtherAttribute" case

**Review by mschwager — APPROVED** [review]
Noice

**Comment by mjambon** [comment]
I don't know how this works but I appreciate the brevity of the code change.

**Comment by nbrahms** [comment]
Needs https://github.com/returntocorp/semgrep-rules/pull/758 merged first

**Comment by aryx** [comment]
This might work but might be slower than the code in in m_list__m_attribute which goes more directly
to the matching keyword or named attribute. It tries to avoid the more costly all_elem_and_rest_of_list.

**Comment by aryx** [comment]
Maybe in practice it does not make much difference, and using the naive m_list_in_any_order is not that much slower.

**Review by colleend — APPROVED** [review]

**Comment by nbrahms** [comment]
Timed on https://github.com/returntocorp/semgrep/runs/941906725; no noticeable difference in performance

**Comment by aryx** [comment]
we might want to delete the m_list__m_attribute() function then. It should be dead now (not sure why ocaml
didn't warn about it).

**Comment by aryx** [comment]
ah I see, because there are more places where we compare attributes.

File: semgrep-core/matching/Generic_vs_generic.ml [hunk 2]
```diff
@@ -1846,7 +1846,7 @@ and m_entity a b =
   { A. name = a1; attrs = a2; tparams = a4; info = a5 },
   { B. name = b1; attrs = b2; tparams = b4; info = b5 } ->
     m_ident_and_id_info_add_in_env_Expr (a1, a5) (b1, b5) >>= (fun () ->
-    (m_list__m_attribute) a2 b2 >>= (fun () ->
+    (m_list_in_any_order ~less_is_ok:true m_attribute a2 b2) >>= (fun () ->
```
Comment (aryx) [inline semgrep-core/matching/Generic_vs_generic.ml:1849]: better to remove the body of m_list__m_attribute and call 
m_list_in_any_order ... in it that way all the places where we look for attributes will have this new behavior.
(need to check the possible perf regression when applied to all the instances).
