### PR TITLE
sym-prop: Fix matching with deep expression patterns

### LINKED ISSUE #3207: [Java] Symbolic expression propagation
**Describe the bug**
Hello team,
Can semgrep expand the expression（Similar to three address codes）？Or is there any other tool that can help me expand the expression in Java? thx :D

**To Reproduce**

Code A and code B are semantically the same.  For code B, I just expanded the expression in code A.
code A:
```java
public final ZipEntry getNextEntry() {
        String name;
        ZipEntry nextEntry = super.getNextEntry();
        if (nextEntry == null || (name = nextEntry.getName()) == null || (!name.contains("../") && !name.contains("..\\"))) {
            return nextEntry;
        }
        throw new SecurityException(":" + nextEntry.getName());
    }
```
code B:
```java
public final ZipEntry getNextEntry() {
        String name;
        ZipEntry nextEntry = super.getNextEntry();
        if (nextEntry == null)
            return nextEntry;
        ZipEntry c = nextEntry;
        name = c.getName();
        if (name == null)
            return nextEntry;
        
        boolean b1 = !name.contains("../");
        boolean b2 = !name.contains("..\\");
        if (b1 && b2)
            return nextEntry;

        throw new SecurityException(":" + nextEntry.getName());
    }
```
The following rule matches code B well, but not code a. 
```
rules:
- id: ZipEntry
  patterns:
    - pattern: $Y = $X.getName();
    - pattern-inside: |
        (ZipEntry $X) = ...;
        ...
        (String $Y) = $X.getName();
        ...
        $Z = <... $Y.contains("...") ...>;
        if (<... $Z ...>) {
          ...
        }

        ...
  languages: 
    - java
  message: |
    match
  severity: WARNING
```

**Expected behavior**

For Java, can semgrep or other tools split expressions into unary or binary expressions?

### PR DESCRIPTION
**Pull request by IagoAbal**
Let's say you want to match pattern:

    return <... name.contains("...") ...>;

against this code:

    boolean b1 = !name.contains("../");
    boolean b2 = !name.contains("..\\");
    return b1 && b2;

It is not enough to compute the subexpressions of `b1 && b2` and then try
matching them with `name.contains("...")`. This does not work. We need to
consider symbolic values *while* computing the subexpressions, so that
`name.contains("../")` and `name.contains("..\\")` are enumerated.

Also allow special ids to be symbolically propagated.

Closes #3207

test plan:
make test # test included

changelog:
Symbolic propagation didn't exist in 0.76.0, but may have ended up there
by mistake when merging the release-0.76.0 branch. The feature never made
it into a release announcement, so I'm adding it for the next one.

PR checklist:
- [ ] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

File: semgrep-core/src/analyzing/Dataflow_svalue.ml [hunk 1]
```diff
@@ -305,6 +305,7 @@ let rec is_symbolic_expr expr =
   match expr.G.e with
   | G.L _ -> true
   | G.N _ -> true
+  | G.IdSpecial _ -> true
```
Comment (aryx) [inline semgrep-core/src/analyzing/Dataflow_svalue.ml:308]: Why IdSpecial was added there? I'm just curious which example we were not handling before.
Do we need all IdSpecial or only a subset?

File: semgrep-core/src/matching/SubAST_generic.ml [hunk 2]
```diff
@@ -93,8 +93,11 @@ let subexprs_of_stmt_kind = function
 let subexprs_of_stmt st = subexprs_of_stmt_kind st.s
 
 (* used for deep expression matching *)
-let subexprs_of_expr e =
+let subexprs_of_expr with_symbolic_propagation e =
   match e.e with
+  | N (Id (_, { id_svalue = { contents = Some (Sym e1) }; _ }))
```
Comment (aryx) [inline semgrep-core/src/matching/SubAST_generic.ml:98]: Shouldn't we allow also when id_svalue is a Lit?

Comment (aryx) [reply semgrep-core/src/matching/SubAST_generic.ml:98]: Actually do we still need Lit now that it can be represented by Sym (Lit ...)?
Or it's still nice to have this special case encoded specially (but then we need to add the invariant somewhere
that we never can have Sym (L ...)

File: semgrep-core/src/matching/SubAST_generic.ml [hunk 3]
```diff
@@ -160,6 +163,10 @@ let subexprs_of_expr e =
   | DisjExpr _ -> raise Common.Impossible
   [@@profiling]
 
+(* Need this wrapper because [@@profiling] has the side-effect of removing labels. *)
```
Comment (aryx) [inline semgrep-core/src/matching/SubAST_generic.ml:166]: If you feel like you want to learn ppx and metaprogramming, you can fix it here :) 
https://github.com/returntocorp/pfff/blob/develop/ppx/ppx_profiling.ml

**Review by aryx — APPROVED** [review]
Awesome!

**Comment by aryx** [comment]
Ok I've fixed the merge conflict with the builtin conflict resolver UI of github.

File: semgrep-core/src/analyzing/Dataflow_svalue.ml (hunk 1 above)
Comment (IagoAbal) [reply semgrep-core/src/analyzing/Dataflow_svalue.ml:308]: Should have made this more clear, but the example I added from #3207 is one case, since we have `boolean b1 = !name.contains("../")` and the `!` is an `IdSpecial(Op)`. I think in general we want all the `IdSpecial` so that e.g. we can propagate `x = this.y`.

File: semgrep-core/src/matching/SubAST_generic.ml (hunk 3 above)
Comment (IagoAbal) [reply semgrep-core/src/matching/SubAST_generic.ml:166]: I actually want. 😄 I had read some articles about it but never actually wrote any PPX extension. I just add this to my to-dos.

File: semgrep-core/src/matching/SubAST_generic.ml (hunk 2 above)
Comment (IagoAbal) [reply semgrep-core/src/matching/SubAST_generic.ml:98]: Good point, that invariant is supposed to hold (you never have `Sym (Lit ...)` so it should be documented and maybe even checked at some places.

We could add `Lit` here too but I believe it is not needed. This is because if `x` equals to `1`,  then as long as `x` is enumerated by `subexprs_of_expr` we are fine.  You can always match `1` against `x` (if `x` is known to be equals to `1`). The problem is when `x` is equals to `!y`, and the pattern is `<... y ...>`. In that case, if only `x` is enumerated,  then `y` cannot be matched directly against `!y`. We need to say that `!y` is a subexpression of `x` so that a recursive call on `!y` will finally yield `y`.
