### PR TITLE
Skip equality AST normalization for Python

### LINKED ISSUE #807: Python `!=` is matched by `not $X`
**Describe the bug**
The pattern:
```
not $X
```
will currently match:
```python
a != b
```

However, this python code actually is called by the interpreter as:
```
type(a).__ne__(a, b)
```
whether any negation at all is performed by the implementation of `__ne__` is at the whim of the programmer of `a`'s type.

**Expected behavior**
This pattern should not match.

**Impact**
This breaks https://semgrep.live/?registry=python.sqlalchemy.correctness.bad-operator-in-filter

**Additional context**
Semgrep version is 0.7.0

https://semgrep.live/lRE

### PR DESCRIPTION
**Pull request by nbrahms**
In Python, == is not necessarily equivalent to !=.

We've already wired up this skip in pfff; this commit merely plumbs it
up within pfff.

Changes were validated by updating the relevant test case.

### CODE REVIEW

**Comment by nbrahms** [comment]
Fixes https://github.com/returntocorp/semgrep/issues/807

**Comment by nbrahms** [comment]
Proper pfff commit is waiting on merge of https://github.com/returntocorp/pfff/pull/117

File: semgrep-core/bin/Main.ml [hunk 1]
```diff
@@ -796,7 +796,7 @@ let options () =
   Common.options_of_actions action (all_actions()) @
   (*e: [[Main_semgrep_core.options]] concatenated actions *)
   [ "-version",   Arg.Unit (fun () ->
-    pr2 (spf "semgrep-core version: %%VERSION%%, pfff: %s" Config_pfff.version);
```
Comment (nbrahms) [inline semgrep-core/bin/Main.ml]: @aryx The build system stuck this in, but I assume this is not correct?

File: semgrep-core/data/basic_equivalences.yml [hunk 2]
```diff
@@ -5,7 +5,7 @@ equivalences:
     languages: [python, javascript, c, go, java]
   - id: eq-to-no-eq
     pattern: $X == $X ==> $X != $X
-    languages: [python, javascript, c, go, java]
+    languages: [javascript, c, go, java]
```
Comment (aryx) [inline semgrep-core/data/basic_equivalences.yml:9]: Maybe add a comment saying why we should not python here.

**Review by aryx — APPROVED** [review]
Looks good.
Yes the %%VERSION%% is a mess we need to fix. Each time you type make
Main.ml gets modified and it's easy to commit that.
We discussed with brendon and martin how to fixed it, simply have a ignored version.ml generated from the Makefile.
