### PR TITLE
Fix AST to IL translation for ternary operators

### LINKED ISSUE #3778: PHP - Taint - Match not detected when in Ternary Operator Assigned to Variable
**Describe the bug**
When trying to reduce duplicate matches of https://github.com/returntocorp/semgrep/issues/3742, by adding functions such as `isset(...)` as sanitizer, I noticed that some code was not detected as tainted

For example: `sink((isset($source) ? $source : 'b'));` is detected, but the below is not

```php
$tainted = (isset($source) ? $source : 'c');
// ruleid:taint-not-detected
sink($tainted);
```

**To Reproduce**
https://semgrep.dev/s/z9zZ

**Expected behavior**
The match should be detected

**What is the priority of the bug to you?**

P1: important to fix or quite annoying

**Environment**
Semgrep.dev & CLI 0.63.0 (installed on MacOSX via Homebrew)

### PR DESCRIPTION
**Pull request by emjin**
The originating expression for the value of a ternary expression should be that ternary expression, not the condition.

Closes #3778 

Test plan: make test

PR checklist:
- [x] documentation is up to date
- [x] changelog is up to date

### CODE REVIEW

**Review by IagoAbal — APPROVED** [review]
Nice!

File: semgrep-core/src/analyzing/AST_to_IL.ml [hunk 1]
```diff
@@ -493,7 +493,7 @@ and expr_aux env eorig =
   | G.Conditional (e1orig, e2orig, e3orig) ->
       let tok = G.fake "conditional" in
       let lval = fresh_lval env tok in
-      let lvalexp = mk_e (Fetch lval) e1orig in
+      let lvalexp = mk_e (Fetch lval) eorig in
```
Comment (aryx) [inline semgrep-core/src/analyzing/AST_to_IL.ml:496]: wow, this is subtle.

**Comment by aryx** [comment]
very nice!
