### PR TITLE
better error outputs and no more pattern validation required

### LINKED ISSUE #386: Pattern Validation is Too Slow
It's taking 56 seconds to do pattern validation. Not sure how much we can improve or if we should just disable for larger rule packs or rely on server-side validation for the registry.

```
 /tmp/test-r  docker run --rm -v "${PWD}:/home/repo" returntocorp/sgrep:develop --config  https://sgrep.live/c/r/r2c.python.django -v
DEBUG is on
trying to download from https://sgrep.live/c/r/r2c.python.django
loaded 1 configs in 1.601447343826294
debug: validated config in 56.35421180725098
running 43 rules from 1 config remote-url
sgrep ran in 0:00:04.733577
{'matches': [], 'errors': []}
 /tmp/test-r  docker run --rm -v "${PWD}:/home/repo" returntocorp/sgrep:develop --config  https://sgrep.live/c/r/r2c.python.django -v --skip-pattern-validation
DEBUG is on
trying to download from https://sgrep.live/c/r/r2c.python.django
loaded 1 configs in 0.8558809757232666
running 43 rules from 1 config remote-url
sgrep ran in 0:00:05.175079
{'matches': [], 'errors': []}

```

### LINKED ISSUE #397: be clear about whether the language passed is supported
**Describe the bug**
sgrep should be clear about whether the language passed is supported when it is not

**To Reproduce**
```
ine@imbp4 ~ [2]> sgrep-lint -e '$X == $X' -l c2 foo
in manual, pattern in rule - can't be parsed for language c2: $X == $X
1 invalid patterns found inside rules; aborting
```
**Expected behavior**
```
ine@imbp4 ~ [2]> sgrep-lint -e '$X == $X' -l c2 foo
language "c2" is not supported, supported languages are ...
```

**Screenshots**

**Environment**
If not using sgrep.live: are you running off docker, an official binary, a local build?

### PR DESCRIPTION
**Pull request by ievans**
- [x] pattern validation is skipped altogether: massive time savings! cuts a lot of code in sgrep-lint and closes #386 
- [x] provide more descriptive exception times in sgrep core and handlers that convert them to structured JSON
- [x] the first invalid pattern will be reported in a JSON message by sgrep core
- [x] sgrep-lint will read the json error report and choose an exit code and friendly user message (decoding the pattern index to actually get all the way back to the user's rule id)
Closes #397 
- [x] introduce more exit codes for various failure types

Addresses some of the points in https://github.com/returntocorp/sgrep/issues/384

### CODE REVIEW

File: sgrep/bin/main_sgrep.ml [hunk 1]
```diff
@@ -540,10 +566,14 @@ let main () =
...
-        if !rules_file <> ""
-        then sgrep_with_rules !rules_file (x::xs)
-        else sgrep_with_one_pattern (x::xs)
-
+        (try (
+          if !rules_file <> ""
+          then sgrep_with_rules !rules_file (x::xs)
+          else sgrep_with_one_pattern (x::xs)
+        ) with exn -> 
+          pr (format_output_exception exn); (* todo, should be pr2 probably *)
```
Comment (ievans) [inline sgrep/bin/main_sgrep.ml:574]: cc @aryx . What is the future of the sgrep CLI? Would it be reasonable to default to JSON output in all cases? Simplifies things for sgrep_lint but I don't have full visibility.

Comment (aryx) [reply sgrep/bin/main_sgrep.ml:574]: I like to have a simple path to test sgrep core functionality. When there's a bug, I prefer to limit as much as possible layers, so I just want one pattern (no yaml file, no sgrep-lint wrapper) and a test file. Before it was bad because there was sgrep_lint.ml and sgrep_generic.ml but now it's mostly the same code behind -e and -rules_file (they both call the same sgrep_generic.ml) so I think it's fine.

Comment (aryx) [inline sgrep/bin/main_sgrep.ml:574]: pr means on stdout, pr2 means on stderr.
I don't know what sgrep-lint captures, I think stdout, so probably good to have pr

File: sgrep/lib/parse_rules.ml [hunk 2]
```diff
@@ -16,16 +16,21 @@ open Common
 
 module R = Rule
 
+exception InvalidRuleException of string * string
```
Comment (aryx) [inline sgrep/lib/parse_rules.ml:19]: I think you can remove the 'Exception' suffix, it's clear from the context that it's an exception.

File: sgrep/lib/parse_rules.ml [hunk 3]
```diff
@@ -52,37 +57,36 @@ let parse file =
...
               pr2_gen x;
-              error "wrong rule fields"
+              raise (InvalidYamlException "wrong rule fields")
          )
-      | _ -> error "missing rules entry"
+      | _ -> raise (InvalidYamlException "missing rules entry as top-level key")
       )
   | Result.Error (`Msg s) ->
-    failwith (spf "sgrep_lint: could not parse %s (error = %s)" file s)
+    raise (UnparsableYamlException s)
```
Comment (aryx) [inline sgrep/lib/parse_rules.ml:89]: note that this yaml file is always generated by sgrep-lint; regular users are not supposed to feed sgrep-core directly with yaml file (except me when I test things), so those errors should be caught by the sgrep-lint wrapper anyway.

**Review by aryx — COMMENTED** [review]
Cool!
Next step is to add line/col position debugging information when a pattern syntax is wrong.

File: sgrep/lib/parse_rules.ml (hunk 2 above)
Comment (ievans) [reply sgrep/lib/parse_rules.ml:19]: Yes, it's just a habit from Python

File: sgrep/lib/parse_rules.ml (hunk 3 above)
Comment (ievans) [reply sgrep/lib/parse_rules.ml:89]: True
