### PR TITLE
[csharp] Fix syntax error in tests/csharp/metavar_call.cs

### LINKED ISSUE #3161: C# tests are broken
Looks like we're getting parse errors on some of our C# tests: https://github.com/returntocorp/semgrep/runs/2631102847?check_suite_focus=true

Also confirmed here:

```
$ cat semgrep-core/tests/csharp/metavar_call.cs | docker run --rm -i returntocorp/semgrep:0.52.0 -e '$X == $X' -l csharp -
ran 1 rules on 1 files: 0 findings
1 files could not be analyzed; run with --verbose for details or run with --strict to exit non-zero if any file cannot be analyzed
```

### PR DESCRIPTION
**Pull request by IagoAbal**
Fixes: 4ca2980cf55 ("C# alpha support (#3121)")

Closes #3161

PR checklist:
- [ ] changelog is up to date

### CODE REVIEW

File: semgrep-core/tests/csharp/metavar_call.cs [hunk 1]
```diff
@@ -1,4 +1,4 @@
-public static void Test
+public static void Test()
```
Comment (mschwager) [inline semgrep-core/tests/csharp/metavar_call.cs]: Does `public` work outside of a class context?

Comment (IagoAbal) [reply semgrep-core/tests/csharp/metavar_call.cs]: My C# knowledge is very rusty, but the tree-sitter grammar accepts this but perhaps it's over-approximating. Do you know C# better? Do I just drop `public`? Otherwise  I can change all the tests to make use of classes.

Comment (IagoAbal) [reply semgrep-core/tests/csharp/metavar_call.cs]: OK I just put everything inside a class so there is no doubt that it is valid C#.

**Review by mschwager — APPROVED** [review]
