### PR TITLE
AST_to_IL: python: Translate async stmts to IL

### LINKED ISSUE #9182: Taint engine does not correctly propagate taint to context managers with the `async` keyword
**Describe the bug**
Python does not properly propagate taint into async context managers - `with $X as $Y` will propagate taint correctly but `async with $X as $Y` will not.

**To Reproduce**
https://semgrep.dev/playground/s/1p1v

**Expected behavior**
Context managers with the `async` keyword should correctly propagate taint.

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [X] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
Semgrep Security Research request

### PR DESCRIPTION
**Pull request by IagoAbal**
Closes #9182

test plan:
make test # new test

### CODE REVIEW

**Comment by aryx** [comment]
I've fixed semgrep-pro; if you rerun the tests it should work.

File: src/analyzing/AST_to_IL.ml [hunk 1]
```diff
@@ -1545,10 +1537,11 @@ and stmt_aux env st =
       ss @ stmt env stmt1
   (* Rust: unsafe block *)
   | G.OtherStmtWithStmt (G.OSWS_Block ("Unsafe", tok), [], stmt1) ->
-      let todo_stmt =
-        mk_s (Instr (mk_fake_TODO_instr ~str:"unsafe_block" env tok))
-      in
-      todo_stmt :: stmt env stmt1
+      let todo_stmt = fixme_stmt ToDo (G.TodoK ("unsafe_block", tok)) in
+      todo_stmt @ stmt env stmt1
+  | G.OtherStmt (OS_Async, [ G.S stmt1 ]) ->
```
Comment (aryx) [inline src/analyzing/AST_to_IL.ml:1542]: we might want to promote OS_Async to a proper stmt if it's a statement in most languages,
or to move it in OtherStmtWithStmt?

**Review by aryx — APPROVED** [review]

File: tests/rules/taint_async.yaml [hunk 2]
```diff
@@ -0,0 +1,16 @@
+rules:
+  - id: test
+    severity: WARNING
+    languages:
+      - python
+    message: Test
+    mode: taint
+    pattern-sources:
```
Comment (aryx) [inline tests/rules/taint_async.yaml:8]: you should use the new syntax and move the test in tests/rules_v2/

**Review by aryx — APPROVED** [review]

File: src/analyzing/AST_to_IL.ml (hunk 1 above)
Comment (IagoAbal) [reply src/analyzing/AST_to_IL.ml:1542]: According to this comment

```ocaml
  (* any here should _not_ contain any statement! otherwise the CFG will be
   * incorrect and some analysis (e.g., liveness) will be incorrect.
```

I think yes we should move it in `OtherStmtWithStmt`.

File: tests/rules/taint_async.yaml (hunk 2 above)
Comment (IagoAbal) [reply tests/rules/taint_async.yaml:8]: Do we have a release date for the new syntax? I'm a bit unsure about doing that, we have a translator from "current syntax" to "new/future syntax", so it's easy to migrate tests later on. But if any detail of the "new syntax" changes in the meantime, that is something we may end up having to fix manually.

Comment (aryx) [reply tests/rules/taint_async.yaml:8]: I think it's good to dogfood. Part of the OSS vs Pro document is looking towards migrating also to the new syntax.

Comment (IagoAbal) [reply tests/rules/taint_async.yaml:8]: Let's discuss via Slack.

File: src/analyzing/AST_to_IL.ml (hunk 1 above)
Comment (IagoAbal) [reply src/analyzing/AST_to_IL.ml:1542]: I left a TODO note for now, I just prefer to have that change in a different PR. If you think that is urgent I can try open one this week.
