### PR TITLE
fix(matching): simplify cast matching and fix double matching bug

### LINKED ISSUE #7403: Duplicate search-mode matches when target has an explicit cast
**Describe the bug**
Matches for patterns containing casts produce duplicates, one including the cast and one without.

See https://github.com/returntocorp/semgrep/pull/7109

**To Reproduce**
https://semgrep.dev/s/0wlB

**Expected behavior**
This should return one finding, not two.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [X] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Exposed via internal rule-writing efforts

### PR DESCRIPTION
**Pull request by brandonspark**
## What:
This PR fixes a double-matching bug we had.

## Why:
We were getting a double match from matching a `Cast` to a `Cast`, because we would match once for the constituents and once for the whole expressions.

## How:
We apply the same logic as symbolic propagation, to only descend into the constituents if we are not already at the root.

## Test plan:
image

## Alternatives considered:

I tried applying @IagoAbal 's suggestion for simplifying the matching logic, by changing it to 
```
  | _, B.Cast (b1, bt, b2) ->
      (match a.G.e with
      | G.Cast (a1, at, a2) ->
          m_type_ a1 b1 >>= fun () ->
          m_tok at bt >>= fun () -> m_expr a2 b2
      | _ -> fail ())
      >||> if not is_root then m_expr a b2 else fail ()
```

However, on either side you place it of the `N _, _ when is_metavariable` case, this causes problems. If it's before, you get issues with `N <mvar>, Cast` case, because it's possible to not produce a match (when it's not at the root), even though you still want that match to occur.

Closes #7403 

PR checklist:

- [X] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [X] Tests included or PR comment includes a reproducible test plan
- [X] Documentation is up-to-date
- [X] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

File: changelog.d/gh-7403.fixed [hunk 1]
```diff
@@ -0,0 +1,4 @@
+Matching: Fixed a bug where explicit casts of expressions would produce two matches to
```
Comment (IagoAbal) [inline changelog.d/gh-7403.fixed:1]: I think it's simpler than this, any expression pattern `E` matches `E` as well as `(T) E`. And e.g. `x` matches `x` and `(int) x`.

**Review by IagoAbal — APPROVED** [review]
I need to convince myself better than we really need `~arguments_have_changed`, but the fix is good anyways.

However, please add a test case, it's easy to make one that works for semgrep-core, simply add a new line as here https://semgrep.dev/s/6YNq.

**Review by aryx — APPROVED** [review]
