### PR TITLE
feat(autofix): aligned fixes

### LINKED ISSUE #3070: Multiline auto-fix indentation is wrong
**Describe the bug**
If a user inputs an autofix that is multiple lines, all lines after the first are indented on an absolute basis rather than relative to the first line. 

**To Reproduce**
`semgrep --config https://semgrep.dev/s/chmccreery:autofix-multiline --autofix --disable-nosem --skip-unknown-extensions --dryrun`

^ Run the above command in /semgrep repository (or create a test repo and copy-paste the test code from https://semgrep.dev/s/chmccreery:autofix-multiline

**Expected behavior**
If an autofix is multiple lines long, and are left-aligned with respect to one another, I expect them to be inserted into the code still left-aligned. This likely means replacing all \n characters in the fix with however many spaces came before the first line. 

**Screenshots**

Screen Shot 2021-05-10 at 2 58 06 PM

**What is the priority of the bug to you?**
P1

**Environment**
semgrep version 0.50.1 (note that autofix in the playground is completely independent from autofix in semgrep). This ticket is specifically to fix the CLI autofix behavior.

### PR DESCRIPTION
**Pull request by brandonspark**
## What:
This PR makes it so that autofixes with newlines involved now try to synchronize the indentation of the inserted lines.

## Why:
Autofix right now is pretty blunt, and just pastes the literal fix text into the file, plus interpolation of metavariables and stuff.

This is usually OK, but is weird in the multiline case. For instance, if I have the following fix:
```
foo()
bar()
```
if I replace in this target:
```
def f():
  to_replace()
```
I will get
```
def f():
  foo()
bar()
```

This is because inserting the literal string `"foo()\nbar()` doesn't account for the fact that the newline will send the `bar()` all the way to the left, which is out of sync with the start of the replacement, which was at a non-zero column.

## How:
This PR just pads every line after the first to make the columns align.

## Test plan:
Automated tests.

Closes #3070

### CODE REVIEW

**Comment by adamboros** [comment]
Will this fix #5701 and #6163 (or conflict with it's proposed fix #8691)?

**Comment by brandonspark** [comment]
@adamboros the former doesn't have any active playground links anymore, so I'm not sure, but I don't think it should fix the latter (nor conflict with the existing PR)

**Comment by aryx** [comment]
need to update some snaphots for the CI failure I think.

File: src/fixing/Autofix.ml [hunk 1]
```diff
@@ -181,6 +229,9 @@ let ast_based_fix ~fix (start, end_) (pm : Pattern_match.t) : Textedit.t option
         Autofix_printer.print_ast ~lang ~metavars ~target_contents
           ~fix_pattern_ast ~fix_pattern fixed_pattern_ast
       in
+      let text =
+        align_text_at_column ~start_column:(fst pm.range_loc).pos.column text
```
Comment (nmote) [inline src/fixing/Autofix.ml]: I don't think this is right:

1. Won't this lead to double-indenting of the first line? I see that you've added tests, but there are quite a few different code paths that autofix can go through given the complexities of osemgrep vs pysemgrep and AST-based vs text-based autofix, so I'm worried that something may not be getting exercised here.
2. I think this will also cause issues if the autofix is applied partway through a line. There seems to be an implicit assumption here that an entire line is matched.

File: src/fixing/Autofix.ml [hunk 2]
```diff
@@ -208,10 +259,12 @@ let ast_based_fix ~fix (start, end_) (pm : Pattern_match.t) : Textedit.t option
 
 let basic_fix ~(fix : string) (start, end_) (pm : Pattern_match.t) : Textedit.t
     =
+  let start_column = (fst pm.range_loc).pos.column in
```
Comment (nmote) [inline src/fixing/Autofix.ml:269]: Same worry here.

File: src/engine/Unit_engine.ml [hunk 3]
```diff
@@ -521,8 +521,11 @@ let autofix_tests_for_lang ~polyglot_pattern_path files lang =
                    | Ok fix_regex_file -> (
                        match UFile.cat fix_regex_file with
                        | [ l1; l2 ] -> FixRegex (l1, None, l2)
-                       | [ l1; l2; l3 ] ->
-                           FixRegex (l1, Some (int_of_string l2), l3)
+                       | l1 :: l2 :: l3 :: rest ->
+                           FixRegex
+                             ( l1,
+                               Some (int_of_string l2),
+                               String.concat "\n" (l3 :: rest) )
```
Comment (nmote) [inline src/engine/Unit_engine.ml:530]: What's the deal here? Is this related?

File: changelog.d/gh-3070.fixed [hunk 4]
```diff
@@ -0,0 +1,2 @@
+Autofix: Fixes that span multiple lines will now try to align
+inserted fixed lines with each other.
```
Comment (nmote) [inline changelog.d/gh-3070.fixed:2]: But only in fixes applied in OCaml, right? So osemgrep or ast-based autofix?

**Review by nmote — COMMENTED** [review]
Would like to see a manual test plan invoking `semgrep` directly as well given the complexities involved here. Perhaps including something that we know has pysemgrep apply the autofixes (--legacy?).

File: src/fixing/Autofix.ml (hunk 1 above)
Comment (brandonspark) [reply src/fixing/Autofix.ml]: This may not be clear from the name of the function, but `align_text_at_column` actually ignores the first line. I'll give it a more descriptive name / comment.

For the second point, I think this would actually depend on what our desired behavior is.

For instance, suppose we match `bar` in the line:
```
foo.bar.x
```
and we replace with the code
```
a()
b()
```
Now, this is already a pretty weird thing to do, but do we care if the result is:
```
foo.a()
b().x
```
or
```
foo.a()
    b().x
```

I believe that the current behavior would produce the former, and my change would produce the latter. I think it actually makes more sense to have the updated behavior.

I can't think of a use case where this matters, but maybe you can.

File: changelog.d/gh-3070.fixed (hunk 4 above)
Comment (brandonspark) [reply changelog.d/gh-3070.fixed:2]: Since https://github.com/semgrep/semgrep/pull/9229, we have been generating all autofixes in OCaml, and then choosing to apply it in either `pysemgrep` or `osemgrep`. So, this should be the source of truth for all autofixes.

File: src/engine/Unit_engine.ml (hunk 3 above)
Comment (brandonspark) [reply src/engine/Unit_engine.ml:530]: This is related to the `fix-regex` test protocol, which previously assumed that the first line would be the regex to match, the second line was the number of matches to replace, and the third line the replacement text. This didn't allow for multiline replacements, though, so I changed this code slightly to allow multiline replacements.

I can leave a comment (the old one became outdated with this, actually)

File: src/fixing/Autofix.ml (hunk 1 above)
Comment (nmote) [reply src/fixing/Autofix.ml]: Yeah, I guess it's kind of a weird thing to do either way. I'm okay with the behavior you propose.

**Review by nmote — APPROVED** [review]
Makes sense, nice work!
