### PR TITLE
core: engine: metavariable-pattern: Fix location info

### LINKED ISSUE #3503: pattern-not-regex doesn't work when under metavariable-pattern
**Describe the bug**

In the following (simplified) structure

```yml
      - metavariable-pattern:
          metavariable: $VALUE
          patterns:
            - pattern-not-regex: ^[0-9]+$
```

It seems like the `pattern-not-regex` is ignored. `pattern-regex` works as expected however.

**To Reproduce**

https://semgrep.dev/s/WOLj

**Expected behavior**

`pattern-not-regex` should work

**Screenshots**

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

### PR DESCRIPTION
**Pull request by IagoAbal**
File, file content, and Generic AST, must all have consistent location
info. This was being done when using the `language` sub-key but not
otherwise, yet it is still needed e.g. when using `pattern-regex`.

Closes #3503

test plan:
make test # tests included

PR checklist:
- [x] documentation is up to date
- [x] changelog is up to date

### CODE REVIEW

File: semgrep-core/src/core/ast/Map_AST.ml [hunk 1]
```diff
@@ -1099,3 +1099,21 @@ let (mk_visitor : visitor_in -> visitor_out) =
...
+let mk_fix_token_locations fix =
+  mk_visitor
+    {
+      default_visitor with
+      kstmt =
+        (fun (k, _) s ->
+          k
+            {
+              s with
+              s_range = Common.map_opt (fun (x, y) -> (fix x, fix y)) s.s_range;
```
Comment (aryx) [inline semgrep-core/src/core/ast/Map_AST.ml:1116]: good call, I would have forgotten that one.

File: semgrep-core/src/engine/Match_rules.ml [hunk 2]
```diff
@@ -647,7 +647,13 @@ and satisfies_metavar_pattern_condition env r mvar opt_xlang formula =
         mvar;
       false
   | Some mval -> (
+      (* We will crete a temporary file with the content of the metavariable,
```
Comment (aryx) [inline semgrep-core/src/engine/Match_rules.ml]: typo, crete -> create

**Review by aryx — APPROVED** [review]

File: semgrep-core/src/core/ast/Map_AST.ml (hunk 1 above)
Comment (IagoAbal) [reply semgrep-core/src/core/ast/Map_AST.ml:1116]: I forgot too, but the tests reminded me about it!
