### PR TITLE
tainting: Track taint coming from params' default values

### LINKED ISSUE #6298: Taint mode does not identify Python keyword arguments as a source
**Describe the bug**
In this example, https://semgrep.dev/s/4v4l, I want to match any instance of a string beginning with `http://` that enters the sinks specified. This works in the expected case, but does not work when the string is the default string of a keyword argument.

**To Reproduce**
https://semgrep.dev/s/4v4l

**Expected behavior**
I expect this rule to match on lines 28 and 38 as it's written.

**Screenshots**
image

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

Switching older "fake taint" rules to taint mode

### PR DESCRIPTION
**Pull request by IagoAbal**
Plus a small refactoring, to make -dfg_tainting use the same code as for running taint rules, otherwise results can differ sometimes.

Closes #6298
Fixes PA-1991

test plan:
make test # added one test

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

File: semgrep-core/src/engine/Match_tainting_mode.ml [hunk 1]
```diff
@@ -495,22 +495,31 @@ let check_fundef lang options taint_config opt_ent fdef =
     let* name = AST_to_IL.name_of_entity ent in
     Some (D.str_of_name name)
   in
-  let add_to_env env id ii =
+  let add_to_env env id ii pdefault =
+    pr2 (spf "add_to_env %s pdefault?=%b" (fst id) (Option.is_some pdefault));
```
Comment (aryx) [inline semgrep-core/src/engine/Match_tainting_mode.ml]: remaining pr2 ...
Maybe we need to add a semgrep rule to forbid them.

Comment (aryx) [reply semgrep-core/src/engine/Match_tainting_mode.ml]: use logger#debug if you really need.

File: semgrep-core/src/engine/Match_tainting_mode.mli [hunk 2]
```diff
@@ -20,6 +20,14 @@ val taint_config_of_rule :
   unit) ->
   Dataflow_tainting.config * debug_taint * Matching_explanation.t list
 
+val check_fundef :
```
Comment (aryx) [inline semgrep-core/src/engine/Match_tainting_mode.mli:23]: Maybe a small comment explaining the function and its arguments.
We should try to have better documentation in our .mli.

**Review by aryx — APPROVED** [review]

File: semgrep-core/tests/rules/taint_param_default.yaml [hunk 3]
```diff
@@ -0,0 +1,29 @@
+rules:
+  - id: request-session-with-http
+    options:
+      symbolic_propagation: true
+    mode: taint
+    pattern-sources:
+      - patterns:
+          - pattern: $URL
```
Comment (aryx) [inline semgrep-core/tests/rules/taint_param_default.yaml:8]: hmm should be "$URL"?
or maybe pattern: |
  "$URL"
(I hate yaml).

**Review by aryx — APPROVED** [review]

File: semgrep-core/src/engine/Match_tainting_mode.ml (hunk 1 above)
Comment (IagoAbal) [reply semgrep-core/src/engine/Match_tainting_mode.ml]: Ooops, sorry, that's meant to go away. Good catch.

File: semgrep-core/src/engine/Match_tainting_mode.mli (hunk 2 above)
Comment (IagoAbal) [reply semgrep-core/src/engine/Match_tainting_mode.mli:23]: True, thanks for calling me out here.

File: semgrep-core/tests/rules/taint_param_default.yaml (hunk 3 above)
Comment (IagoAbal) [reply semgrep-core/tests/rules/taint_param_default.yaml:8]: Good point, I guess they may be using `metavariable-pattern` instead of `metavariable-regex` because then they can use `pattern-not-regex` ? cc @minusworld
