### PR TITLE
fix(pro): report semgrep pro errors nicely

### LINKED ISSUE #7028: [deep semgrep] `semgrep --interfile` fails with wrong, generic error message
**Describe the bug**

A useless error message is produced when semgrep is invoked with the `--interfile` option and `semgrep-core-proprietary` fails to parse a rule due to an invalid pattern.

Since #5996 , the error message is:
```
Exception raised: `Error while running rules: semgrep-core exited successfully but produced unexpected output`
```
It used to be:
```
Exception raised: `Error while running rules: 0 bytes read on a total of 2 expected bytes`
```

* Replacing `semgrep-core-proprietary` by a copy of `semgrep-core` doesn't change a thing.
* Using `--pro` works fine. It's the error reporting with `--interfile` that's broken.
* `semgrep-core-proprietary`, when run alone, exits with code 2, unlike what the new error message claims (sorry about that - @mjambon)

**To Reproduce**

```
$ cat toto.yaml 
rules:
  - id: apex.injection.soql-injection
    severity: ERROR
    languages:
      - python
    message: foo
    pattern: "if True:"
```

This is the semgrep command that shows the unhelpful error message. Note that to reproduce the problem, you can copy the regular `semgrep-core` to the `bin/` folder where `semgrep-core-proprietary` is expected:
```
$ semgrep scan --config toto.yaml --interfile
Scanning 19 files.
!!!This is a proprietary extension of semgrep.!!!
!!!You must be logged in to access this extension!!!
Using Semgrep Pro installed in /home/martin/semgrep/cli/src/semgrep/bin/semgrep-core-proprietary
Semgrep Pro Version Info: (0.13.0-96-g526b2f0)
    0%|                                                              |0/19 tasks

Semgrep Pro crashed during execution (unknown reason).
This can sometimes happen because either Semgrep Pro or Semgrep is out of date.

Try updating your version of Semgrep Pro (`semgrep install-semgrep-pro`) or your version of Semgrep (`pip install semgrep/brew install semgrep`).
If both are up-to-date and the crash persists, please contact support to report an issue!
When reporting the issue, please re-run the semgrep command with the
`--debug` flag so as to print more details about what happened, if you can.

Exception raised: `Error while running rules: semgrep-core exited successfully but produced unexpected output`
                    
    0%|                                                              |0/19 tasks
```

**Expected behavior**

This the desired output that we get without the `--interfile` option:
```
$ sg scan --config toto.yaml
Scanning 19 files.
    0%|                                                              |0/19 tasks
[ERROR] Pattern parse error in rule apex.injection.soql-injection:
 Invalid pattern for Python:
--- pattern ---
if True:
--- end pattern ---
Pattern error: Parsing.Parse_error
```

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**

CLI, normal build on Linux

**Use case**

Allow any user of `--interfile` to see what's wrong when they write an invalid pattern (or possibly other kinds of errors) without going through the Semgrep Playground.

### PR DESCRIPTION
**Pull request by emjin**
Closes https://github.com/returntocorp/semgrep/issues/7028

Previously reported crashes for routine errors (including user errors) due to how errors were caught. This is now fixed

Test plan: pull changes from PR 580 in semgrep-pro. Then create a file with a pattern parse error. Run from anywhere

`semgrep --config <config> . --pro`

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

File: changelog.d/gh-7028.fixed [hunk 1]
```diff
@@ -0,0 +1 @@
+Fix: Semgrep Pro previously reported a crash for normal errors. This fixes that
```
Comment (brandonspark) [inline changelog.d/gh-7028.fixed]: nit: "this fixes that" is pretty informal / spurious. also, what does "normal error" mean? could we give an example of an error?

File: cli/src/semgrep/core_runner.py [hunk 2]
```diff
@@ -992,7 +992,11 @@ def _run_rules_direct_to_semgrep_core(
             return self._run_rules_direct_to_semgrep_core_helper(
                 rules, target_manager, dump_command_for_core, engine
             )
+        except SemgrepError as e:
+            # Handle Semgrep errors normally
+            raise e
         except Exception as e:
```
Comment (brandonspark) [inline cli/src/semgrep/core_runner.py:998]: oops i think i wrote this

**Review by brandonspark — APPROVED** [review]

File: changelog.d/gh-7028.fixed (hunk 1 above)
Comment (emjin) [reply changelog.d/gh-7028.fixed]: I need chatgpt to write changelog entries for me I never like doing it
