### PR TITLE
Fix Stack_overflow when using -filter_irrelevant_rules

### LINKED ISSUE #4305: [PHP] Stack overflow with big list of pattern-inside
See https://r2c-community.slack.com/archives/C018NJRRCJ0/p1637242553127900

### PR DESCRIPTION
**Pull request by aryx**
This closes #4305

test plan:
test file included

PR checklist:
- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

File: semgrep-core/src/optimizing/Analyze_rule.ml [hunk 1]
```diff
@@ -517,8 +522,14 @@ let regexp_prefilter_of_rule r =
...
-      | R.Taint spec -> regexp_prefilter_of_taint_rule t spec)
+      try
+        match r.mode with
+        | R.Search pf ->
+            let f = R.formula_of_pformula pf in
+            regexp_prefilter_of_formula f
+        | R.Taint spec -> regexp_prefilter_of_taint_rule t spec
+      with
+      (* TODO: see tests/OTHER/rules/tainted-filename.yaml *)
+      | Stack_overflow ->
```
Comment (IagoAbal) [inline semgrep-core/src/optimizing/Analyze_rule.ml:533]: `regexp_prefilter_of_taint_rule` already has a top-level `try-with`, maybe one could just add a case for `| Stack_overflow ->` there?

**Review by IagoAbal — APPROVED** [review]

File: semgrep-core/src/optimizing/Analyze_rule.ml (hunk 1 above)
Comment (aryx) [reply semgrep-core/src/optimizing/Analyze_rule.ml:533]: yes, good idea.

Comment (aryx) [reply semgrep-core/src/optimizing/Analyze_rule.ml:533]: hmm but then I don't have the rule id to logger the issue
simpler to keep there then.
