### PR TITLE
Fix the String.rindex_from exn

### LINKED ISSUE #8792: osemgrep: `String.rindex_from` raising `Invalid_argument`
**Describe the bug**

I was debugging and left some `logger#flash` or something around. When I was committing, I got an `Invalid_argument` exception in this function:

File src/osemgrep/Matches_report.ml:
```ocaml
let wrap ~indent ~width s =
  let pre = String.make indent ' ' in
  let rec go indent width pre s acc =
    let real_width = width - indent in
    if String.length s <= real_width then List.rev ((pre, s) :: acc)
    else
      let cut =
        let prev_ws =
          try String.rindex_from s real_width ' ' with
          | Not_found -> 0
        and prev_dash =
          try 1 + String.rindex_from s real_width '-' with
          | Not_found -> 0
        in
        let m = max prev_ws prev_dash in
        if m = 0 then real_width else m
      in
 ...
```

I think it's worthwhile double-checking that `real_width` here is always within bounds.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?

### PR DESCRIPTION
**Pull request by aryx**
This closes #8792 

test plan:
launch a terminal (e.g., xterm) and reduce its columns to 8 or less, introduce a finding (e.g., use == in Test_jsoo.ml), and then run ./bin/osemgrep --experimental --config semgrep.jsonnet js/tests/Test_jsoo.ml) and now it does not crash anymore

### CODE REVIEW

**Comment by aryx** [comment]
This is related to https://github.com/returntocorp/semgrep/issues/8792

File: src/osemgrep/reporting/Matches_report.ml [hunk 1]
```diff
@@ -18,6 +18,7 @@ let findings_indent_depth = String.make 12 ' '
 let text_width =
   let max_text_width = 120 in
   let w = Option.value ~default:max_text_width (Terminal_size.get_columns ()) in
+  (* TODO: what is this w - (w - 100) ? What if w <= 5? *)
   if w <= 110 then w - 5 else w - (w - 100)
```
Comment (hannesm) [inline src/osemgrep/reporting/Matches_report.ml:22]: taken from cli/src/semgrep/formatter/text.py:

```python
if width <= 110:
    width = width - 5
else:
    width = width - (width - 100)
```

Comment (aryx) [reply src/osemgrep/reporting/Matches_report.ml:22]: I know it's taken from text.py, I still don't really understand why we do that

**Review by hannesm — APPROVED** [review]
looks good to me.
