### PR TITLE
C: Const prop not working in stack array decls

### LINKED ISSUE #8037: Constant propagation not happening in basic C function case
**Describe the bug**
The function is simply:
```
void fun() {
  int fixed = 42;
  // ruleid: match_fixed_size_buffer
  char a[42];
  // ruleid: match_fixed_size_buffer
  char b[fixed];
  // ok: match_fixed_size_buffer
  char c[unknown];
}
```

But the rule
```
rules:
  - id: match_fixed_size_buffer-copy
    patterns:
      - pattern: |
          $TYPE $BUF[42];
    message: var $BUF - size $SIZE
    languages:
      - c
    severity: WARNING
```
fails to match

**To Reproduce**
https://semgrep.dev/playground/s/b36Q

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

### PR DESCRIPTION
**Pull request by yosefAlsuhaibani**
closes #8037 

It used to be the case that we weren't able to match the following with the pattern `$TYPE $NAME[404];`:
```c
int main() {
  int bad = 404;
  #ERROR:
  int arr[bad]; //old semgrep wouldn't match this line!
  return 0;
}
```
but now we do; the fix is by translating array decls as follows in IL:
```
_tmp := bad 
DEF arr
```

test plan: `make test` + wrote a couple of test sets in `semgrep/tests/patterns/c`; one that is straight line code and the other has nested control flow.

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure about any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

File: changelog.d/gh-8037.fixed [hunk 1]
```diff
@@ -0,0 +1,13 @@
+Constant propagation is now applied to declerations inside stack array declerations in C; so
```
Comment (aryx) [inline changelog.d/gh-8037.fixed]: typo declerations (2 times)

**Review by aryx — APPROVED** [review]

File: changelog.d/gh-8037.fixed (hunk 1 above)
Comment (yosefAlsuhaibani) [reply changelog.d/gh-8037.fixed]:
```
Error: Unbound value declerations 
Hint: did you mean declarations?
```

**Review by emjin — APPROVED** [review]
Nice!

File: changelog.d/gh-8037.fixed [hunk 2]
```diff
@@ -0,0 +1,13 @@
+Constant propagation is now applied to declarations inside stack array declarations in C; so
```
Comment (IagoAbal) [inline changelog.d/gh-8037.fixed]: I believe you wanted to write "... is now applied inside stack array ..." and the "to declarations" that is there in the middle may be the result of you having rewritten this sentence?

Comment (yosefAlsuhaibani) [reply changelog.d/gh-8037.fixed]: Ah Indeed; removed the `declarations inside`.

File: src/analyzing/AST_to_IL.ml [hunk 3]
```diff
@@ -1241,6 +1241,14 @@ and stmt_aux env st =
       let ss, e' = expr_with_pre_stmts env e in
       let lv = lval_of_ent env ent in
       ss @ [ mk_s (Instr (mk_i (Assign (lv, e')) (Related (G.S st)))) ]
+  | G.DefStmt (ent, G.VarDef { G.vinit = None; vtype = Some ty }) -> (
```
Comment (IagoAbal) [inline src/analyzing/AST_to_IL.ml]: I think it's better to write this pattern instead:
```
... vtype = Some { t = G.TyArray ((_, Some e, _), _); _} ...
```
so that if it's not an array type as you want, then we don't end up in your default `[]` case, which is "masking" whatever the default case used to be.

**Comment by emjin** [comment]
uhh yikes the benchmarks are probably not you

File: src/analyzing/AST_to_IL.ml [hunk 4]
```diff
@@ -1241,6 +1241,14 @@ and stmt_aux env st =
...
+      match ty.t with
+      | G.TyArray ((_, Some e, _), _) ->
+          let ss, e' = expr_with_pre_stmts env e in
```
Comment (IagoAbal) [inline src/analyzing/AST_to_IL.ml]: Also it's worth having a comment here explaining what is the purpose of this.

**Review by IagoAbal — APPROVED** [review]
