### PR TITLE
tainting: Allow propagation of taint through lambdas

### LINKED ISSUE #5971: Taint mode bug when matching the foreach statement
**Describe the bug**
The taint mode might not track data flow through `foreach` statement

**To Reproduce**
https://semgrep.dev/s/94LY

**Expected behavior**
The `foreach` statement should be tracked and the sink function in the provided code should be matched.

**What is the priority of the bug to you?**
P1: important to fix or quite annoying. It might ignore lots of potential findings in the code

**Environment**
https://semgrep.dev/playground/

**Use case**
Tried to do taint mode analysis in the source code to do the security research and audit.

### PR DESCRIPTION
**Pull request by IagoAbal**
... via `pattern-propagators`.

This is useful for propagating taint through higher-order iterators such as `forEach` in Java.

Closes #5971
Closes PA-1813

test plan:
make test # added three tests

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

File: semgrep-core/tests/rules/taint_propagator_lambda.java [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+    }
+
+    public void func3() {
+        String nodePred = request.getParameter("h");
+        NodeSucc nodeSucc = new NodeSucc(nodePred);
+        //ruleid: test
+        Runtime.getRuntime().exec(nodeSucc);
+    }
+
+    public void func4() {
```
Comment (aryx) [inline semgrep-core/tests/rules/taint_propagator_lambda.java:28]: This feels like it should be the only tests.
What are testing the other func1/func2/func3?
I don't even see the difference between their code.

**Review by aryx — APPROVED** [review]

File: semgrep-core/tests/rules/taint_propagator_lambda.java (hunk 1 above)
Comment (IagoAbal) [reply semgrep-core/tests/rules/taint_propagator_lambda.java:28]: That was the example reported by the user. For debugging, I always minimize the example. But for testing, I tend to include it as-is, with the hope to increase coverage.

Comment (IagoAbal) [reply semgrep-core/tests/rules/taint_propagator_lambda.java:28]: Clarified this in the test file. I think the other cases are useful to increase the test coverage of taint-mode, but we could perhaps separate non-minimized user-provided examples?
