### PR TITLE
[Go] Fix matching of module file paths

### LINKED ISSUE #3484: `import "foobar"` matched `import "foobar4"` in golang
**Describe the bug**
`import "foobar"` matched `import "foobar4"` in golang

**To Reproduce**
https://semgrep.dev/s/AwNw

**Expected behavior**
I expect L19, 21, 25, 27 not to match, but they do.

**What is the priority of the bug to you?**
- [x] P2: regular bug that should get fixed

cc @aryx @IagoAbal

### PR DESCRIPTION
**Pull request by IagoAbal**
Closes #3484

test plan:
make test # test included

PR checklist:
- [x] documentation is up to date
- [x] changelog is up to date

### CODE REVIEW

File: semgrep-core/src/matching/Matching_generic.ml [hunk 1]
```diff
@@ -658,21 +658,29 @@ let m_string a b = if a =$= b then return () else fail ()
 
 (*e: function [[Matching_generic.m_string]] *)
 
-(*s: function [[Matching_generic.string_is_prefix]] *)
-let string_is_prefix s1 s2 =
+(*s: function [[Matching_generic.filepath_is_prefix]] *)
```
Comment (aryx) [inline semgrep-core/src/matching/Matching_generic.ml:661]: Do not modify those comments. They will prevent me to sync the code with some documentation I have on the side.
I know this function changed names, but just do not care about those comments.

**Review by aryx — APPROVED** [review]
