### PR TITLE
fix(js): Faithfully represent import statements in generic AST

### LINKED ISSUE #5305: TS/JS - Import drops $VALUE before {...}
**Describe the bug**
The addition [for import { } from 'value' ](https://github.com/returntocorp/semgrep/issues/5012) was awesome for TS/JS  but it also would be great to capture the  values before {..} 

```
  - pattern-inside: |
      import {  ...,useRef,... } from "react"
      ...

^ works

      import React,{  ...,useRef,... } from "react"
      ...

^ does not work 
```

Works:
https://semgrep.dev/playground/s/ylo8?develop=true

Does not work:
https://semgrep.dev/s/ylo8

**To Reproduce**
Works:
https://semgrep.dev/playground/s/ylo8?develop=true

Does not work:
https://semgrep.dev/s/ylo8

**Expected behavior**
$REACT should be also captured 

**Priority**
How important is this to you?
- [x] P2: annoying but not blocking me

### PR DESCRIPTION
**Pull request by nmote**
Previously, a statement such as `import {x, y} from 'z'` would have been desugared into two separate `ImportFrom` statements. This caused issues with matching, such as #5305, and it also led to the issue described in #6532.

This PR changes the `ImportFrom` node to have a list of imported values instead of a single imported value. That allows us to represent the example above as a single `ImportFrom` node without desugaring. It also allows `import {} from 'z';` to be represented (though it's unclear to me why anybody would ever write that). This change addresses the issues mentioned above.

Fixes #5305

Test plan: Automated tests

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Comment by nmote** [comment]
I just updated this PR with some tests that show some more improved matching behavior. Check out `equivalence_import_variations4.js` and compare to https://semgrep.dev/s/B757

File: semgrep-core/src/matching/Generic_vs_generic.ml [hunk 1]
```diff
@@ -3003,16 +3003,15 @@ and m_directive a b =
...
-      let normal_b = Normalize_generic.normalize_import_opt false b.d in
-      match (normal_a, normal_b) with
-      | Some (a0, a1), Some (b0, b1) ->
-          m_tok a0 b0 >>= fun () -> m_module_name_prefix a1 b1
-      | _ -> fail ())
+  (* normalize only if very simple import pattern (no aliases) *)
+  | G.ImportFrom (_, _, imports)
+    when List.for_all
+           (function
+             | _, None -> true
```
Comment (emjin) [inline semgrep-core/src/matching/Generic_vs_generic.ml]: nit: this would be more readable for me if there were underscored names given to the wildcards. In particular, something like `(_name, Some(_aliases))` would let me know what we're filtering for. It's not the norm in this file though so this is fine

File: semgrep-core/src/parsing/pfff/js_to_generic.ml [hunk 2]
```diff
@@ -756,22 +763,22 @@ and require_to_import_in_stmt_opt st =
                          | (s1, _), (s2, _) when s1 =$= s2 -> None
                          | _ -> Some (id2, G.empty_id_info ())
                        in
-                       G.DirectiveStmt
-                         (G.ImportFrom (treq, G.FileName file, id1, alias_opt)
-                         |> G.d)
-                       |> G.s
+                       (id1, alias_opt)
                    | _ -> raise ComplicatedCase)
```
Comment (emjin) [inline semgrep-core/src/parsing/pfff/js_to_generic.ml:767]: lmao this exception

**Review by emjin — APPROVED** [review]
I'm not super familiar with Javascript imports, but this seems straightforward and good to me.  I wonder if there are any SR issues this solves, I know they've had friction with our Javascript imports

File: semgrep-core/src/matching/Generic_vs_generic.ml (hunk 1 above)
Comment (nmote) [reply semgrep-core/src/matching/Generic_vs_generic.ml]: I've made this change and added a comment. Hopefully that's clearer now.

**Comment by nmote** [comment]
Yes, @LewisArdern reported the issue that this closes. Maybe there are others, too.

File: semgrep-core/src/core/ast/AST_generic.ml [hunk 3]
```diff
@@ -1749,8 +1749,7 @@ and directive_kind =
   | ImportFrom of
       tok (* 'import'/'from' for Python *)
       * module_name
-      * ident
-      * alias option (* as name alias *)
+      * (ident * alias option (* as name alias *)) list
```
Comment (aryx) [inline semgrep-core/src/core/ast/AST_generic.ml:1752]: Could we add a comment here explaining why we don't "desugar" in multiple ImportFrom like
we do for variable declarations. I already forgot why we do that ...

Comment (nmote) [reply semgrep-core/src/core/ast/AST_generic.ml:1752]: https://github.com/returntocorp/semgrep/pull/6634
