### PR TITLE
fix(scala): allowed percolation of name information from class parameters

### LINKED ISSUE #5506: Metavariables do not work for object reference in Scala
**Describe the bug**
Metavariables do not work for object reference in Scala

**To Reproduce**
Steps to reproduce the behavior, ideally a link to https://semgrep.dev:
The link is attached https://semgrep.dev/s/zojz

**Expected behavior**
Based on the link, there should be two matches for the pattern, line 3 and line 8.

**Screenshots**

**What is the priority of the bug to you?**
- [ ] P1: important to fix or quite annoying

**Environment**
If not using semgrep.dev: are you running off docker, an official binary, a local build?

**Use case**
What will fixing this bug enable for you?
It allows us to find usage of methods in code base.

### PR DESCRIPTION
**Pull request by brandonspark**
**What:**
Currently, during the naming stage, class parameters are not properly added to the scope. This means that certain identifiers with type information attached to them are not actually known to Semgrep to have those types, if introduced via class parameters. 

**Why:**
We should allow this, because otherwise Semgrep cannot fulfill certain typed metavariable queries.

For instance, in Scala:
```scala
class ExampleClass(val x: TypeName) {
}
```

The identifier `x` should be known to have type `TypeName`, but currently does not.

**How:**
I added some code which adds these parameters to the scope. I used `with_new_function_scope`, even though this is a class scope, since when looking through the code, it seems that this is just a general scoping thing which is undone later. Let me know if that's not the right thing to do, though.

Fixes #5506.

Test plan: `make test`

PR checklist:
- [X] Documentation is up-to-date
- [X] `changelog.d/<issue>.<type>` is a file with the _what_, _why_, and _how_ of the change.
  - \<issue> is `pa-312` (Linear ticket), `gh-1234` (GitHub issue), or `new-gizmo` (unique semantic name)
  - \<type> is `added`, `changed`, `fixed`, or `infra`.
- [X] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see the [Contribution guidelines](https://semgrep.dev/docs/contributing/how-to-contribute/)!

### CODE REVIEW

File: semgrep-core/src/naming/Naming_AST.ml [hunk 1]
```diff
@@ -457,7 +457,9 @@ let resolve lang prog =
           (* todo: we should first process all fields in the class before
            * processing the methods, as some languages may allow forward ref.
            *)
-          with_new_context InClass env (fun () -> k x));
+          let class_params = params_of_parameters env x.cparams in
+          with_new_context InClass env (fun () ->
+              with_new_function_scope class_params env.names (fun () -> k x)));
```
Comment (aryx) [inline semgrep-core/src/naming/Naming_AST.ml:463]: maybe add a (* TODO? maybe we need a with_new_class_scope to handle this? abusing with_new_function_scope for now *)

**Review by aryx — APPROVED** [review]
Great!

Would be nice to also add this feature in deep-semgrep where we have different code to perform naming (basically each time we touch Naming_AST.ml (which BTW is a ugly hack), we need to also update in deep-semgrep Naming_SAST.ml (which is far cleaner)).

**Comment by IagoAbal** [comment]
Great PR comments!

File: changelog.d/gh-5506.fixed [hunk 2]
```diff
@@ -0,0 +1 @@
+Scala/others: Added a fix allowing percolation of name information from class parameters
```
Comment (IagoAbal) [inline changelog.d/gh-5506.fixed:1]: You could elaborate the what/why more here. You could refer to the same example you used in the PR comment:
```Scala
class ExampleClass(val x: TypeName) {
}
```
But you don't need to repeat yourself, if something is explained in the changelog entry you could omit details in the PR comment.
