### PR TITLE
metavariable-pattern: Add support for non-Semgrep patterns

### LINKED ISSUE #3411: metavariable-pattern does not work on metavariables bound by a regex
**Describe the bug**
Once we now bind capture groups to metavariables (`$1`, `$2`, ...) we should be able to filter these matches using `metavariable-pattern`, but this does not seem to work yet.

**To Reproduce**
https://semgrep.dev/s/Dwko

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

### PR DESCRIPTION
**Pull request by IagoAbal**
This allows metavariable-pattern to invoke the Spacegrep, regex, and
Comby engines.

Closes #3411

test plan:
make test # test included

PR checklist:
- [x] changelog is up to date

### CODE REVIEW

File: semgrep-core/src/engine/Match_rules.ml [hunk 1]
```diff
@@ -801,36 +785,57 @@ and range_matches_with_pattern env r mvar opt_lang formula =
...
-           Parse_target.parse_and_resolve_name_use_pfff_or_treesitter lang file
-         in
-         let ast = fix_toks ast in
-         if errors <> [] then pr2 (warn_msg ());
-         (ast, errors)))
+                (Some { r with r = mval_range }) )
+      | Some xlang, MV.Text (content, _tok)
+      | Some xlang, MV.E (G.L (G.String (content, _tok))) ->
+          (* We reinterpret the matched text as `xlang`. *)
+          let ext =
```
Comment (aryx) [inline semgrep-core/src/engine/Match_rules.ml:792]: I don't think the extension really matters.  I don't think Parse_target will reject files with the wrong extension

**Review by aryx — APPROVED** [review]
