### PR TITLE
Disable Bloom filter optimization by default

### LINKED ISSUE #4670: [python] multiline strings should be semantically equivalent
**Describe the bug**
In python, multiline strings are semantically equivalent to single-line strings. Semgrep should treat them as such.

**To Reproduce**
https://semgrep.dev/s/q9Yb

**Expected behavior**
Match either single- or multiline-strings with a single pattern

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Use case**
cf. #4669

### PR DESCRIPTION
**Pull request by IagoAbal**
It conflicts with const-prop and sym-prop and appears not to provide a major net benefit nowadays.

To close #4670 we still need to tackle filter-irrelevant-rules interaction with const-prop.

Helps #4670
Helps PR #6179
Closes PA-1927

test plan:
make test # added one test

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Review by emjin — APPROVED** [review]
Yay! Let's review in a month and if nobody has complained, delete it altogether.

File: semgrep-core/src/core/Flag_semgrep.ml [hunk 1]
```diff
@@ -24,8 +24,30 @@ let filter_irrelevant_patterns = ref false
...
+ * Regarding performance, we ran Semgrep with and without this optimization on
+ * nine of the repos in our stress-test monorepo (using p/default):
+ *
+ * - In four cases (elasticsearch, maven, metabase, and kubernetes) using the
+ *   Bloom filter was about 4-5% slower.
+ * - In four cases (hadoop, mypy, react, mediawiki) using the Bloom filter was an
+ *   average of 9.5% faster, with the largest effect seen on mypy (15% faster).
+ * - In the remaining case (flask) there was no meaningful difference.
+ *
+ * That said take these %'s with a grain of salt, since we only did one run each,
```
Comment (aryx) [inline semgrep-core/src/core/Flag_semgrep.ml:45]: great comment! and nice test.
