### PR TITLE
Parse booleans as constants

### LINKED ISSUE #5509: Boolean constant propagation does not behave correctly in PHP
**Describe the bug**
Constant propagation with boolean values does not behave as advertised in PHP.

A rule like 

**To Reproduce**
To illustrate the issue, see the following (correct) Python example:
https://semgrep.dev/s/kPvX

Identical behavior in PHP is not matched as expected:
https://semgrep.dev/s/w2vx

**Expected behavior**
Boolean constant propagation is consistent across languages.

**Screenshots**

**What is the priority of the bug to you?**

- [X] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev, CLI 0.97.0

**Use case**
Required for T1 PHP vuln coverage & PHP GA.

### PR DESCRIPTION
**Pull request by emjin**
Closes https://github.com/returntocorp/semgrep/issues/5509

This allows constant propagation to happen on booleans in PHP by parsing
booleans as constants instead of Id. It adds a new construct to the AST for
bool. This was decided after reading the manual description of boolean, which
does not specify it as equivalent to an int value (see comment).

Test plan: make test

PR checklist:

- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

File: semgrep-core/src/parsing/tree_sitter/Parse_php_tree_sitter.ml [hunk 1]
```diff
@@ -291,6 +291,18 @@ let map_integer env tok =
   let value = int_of_string value in
   A.Int (Some value, tok)
 
+let map_boolean env tok =
+  let bool_of_string value =
+    let true_regexp = Str.regexp "['T''t']['R''r']['U''u']['E''e']" in
+    let false_regexp = Str.regexp "['F''f']['A''a']['L''l']['S''s']['E''e']" in
+    if Str.string_match true_regexp value 0 then true
+    else if Str.string_match false_regexp value 0 then false
```
Comment (nmote) [inline semgrep-core/src/parsing/tree_sitter/Parse_php_tree_sitter.ml]: I like to avoid regexes where possible, since they come with performance penalties, occasional bits of surprising behavior, and generally are not super readable. I'd prefer to replace this with something like the following:

```suggestion
    let canonicalized_value = String.lowercase_ascii value in
    if canonicalized_value = "true" then true
    else if canonicalized_value = "false" then false
```

File: semgrep-core/src/parsing/tree_sitter/Parse_php_tree_sitter.ml [hunk 2]
```diff
@@ -291,6 +291,18 @@ let map_integer env tok =
...
+    else failwith ("Not a valid PHP boolean: " ^ value)
```
Comment (nmote) [inline semgrep-core/src/parsing/tree_sitter/Parse_php_tree_sitter.ml:301]: Is there something less severe than a `failwith` that would be appropriate here?

**Review by nmote — APPROVED** [review]
Overall looks good, just a stylistic suggestion and a question inline.

File: semgrep-core/src/parsing/tree_sitter/Parse_php_tree_sitter.ml (hunk 1 above)
Comment (mmcqd) [reply semgrep-core/src/parsing/tree_sitter/Parse_php_tree_sitter.ml]: I agree, that regex seems overpowered for this task

File: semgrep-core/src/parsing/tree_sitter/Parse_php_tree_sitter.ml (hunk 2 above)
Comment (emjin) [reply semgrep-core/src/parsing/tree_sitter/Parse_php_tree_sitter.ml:301]: I don't think so :( I'll fix it later if it turns out there is
