### PR TITLE
[Java] dataflow: IL: Add partial support for synchronized blocks

### LINKED ISSUE #4150: Constant propagation does not understand synchronized construct
**Describe the bug**
Constant propagation happens even if a variable is reassigned within a `synchronized` block.

**To Reproduce**
https://semgrep.dev/s/rYj0

**Expected behavior**
The returned expression in this function should not be matched.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

### PR DESCRIPTION
**Pull request by IagoAbal**
Closes #4150

test plan:
make test # tests included

PR checklist:
- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

File: semgrep-core/src/analyzing/AST_to_IL.ml [hunk 1]
```diff
@@ -1036,6 +1036,10 @@ let rec stmt_aux env st =
         | _ -> (None, manager_as_pat)
       in
       python_with_stmt env manager opt_pat body
+  (* Java: synchronized (E) S *)
+  | G.OtherStmt (G.OS_Sync, [ G.E objorig; G.S stmt1 ]) ->
```
Comment (aryx) [inline semgrep-core/src/analyzing/AST_to_IL.ml:1040]: hmm, it should be a OtherStmtWithStmt then. We should remove G.OS_Sync and move it under OtherStmtWithStmt.

**Review by aryx — APPROVED** [review]

File: semgrep-core/src/analyzing/AST_to_IL.ml (hunk 1 above)
Comment (IagoAbal) [reply semgrep-core/src/analyzing/AST_to_IL.ml:1040]: I will open a separate PR for that.
