### PR TITLE
AST_to_IL: Translate if-then-else as expressions

### LINKED ISSUE #4965: Taint mode does not handle conditional assignment in Ruby correctly
**Describe the bug**
Ruby supports conditional assignment:

```ruby
foo = if hash[:key]
        hash[:key]
      else
        default_value
      end
```

**To Reproduce**
A minimal example is here: https://semgrep.dev/s/ALK6
This functionality is required to port a Brakeman rule correctly based on this set of test cases: https://semgrep.dev/s/returntocorp:check-symbol-dos

**Expected behavior**
Taint should propagate through conditional assignment.

**Screenshots**
N/A

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying - this is blocking completion of a Brakeman check for Ruby < 2.2 / Rails < 5.0
- [ ] P2: regular bug that should get fixed

**Environment**
semgrep.dev

**Use case**
Porting Brakeman rules, Ruby behavior correctness

### PR DESCRIPTION
**Pull request by IagoAbal**
We supported if-then-else statements, but not expressions as in OCaml,
Ruby, etc.

Closes #PA-1118
Closes #4965

test plan:
make test # test included

PR checklist:

- [x] Documentation is up-to-date
- [x] Changelog is up-to-date
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

**Comment by aryx** [comment]
FYI the ruby parser in pfff comes from the diamondruby project, which defined also a Ruby IL (see pfff/lang_ruby/analyze/il_ruby.ml) that does some of those transformations. FYI here was the paper about it: https://www.cs.umd.edu/~mwh/papers/ril.pdf

File: semgrep-core/src/analyzing/AST_to_IL.ml [hunk 1]
```diff
@@ -796,6 +789,41 @@ and record env ((_tok, origfields, _) as record_def) =
...
 
+and stmt_expr env ?e_gen st =
+  let todo () =
+    match e_gen with
+    | None -> todo (G.E (G.e (G.StmtExpr st)))
+    | Some e_gen -> todo (G.E e_gen)
+  in
+  match st.G.s with
+  | G.ExprStmt (eorig, _) -> expr env eorig
+  | G.If (tok, cond, st1, opt_st2) ->
```
Comment (aryx) [inline semgrep-core/src/analyzing/AST_to_IL.ml:800]: again maybe a comment like   IF <cond> <then> <else> --> ???
to get an overview of the transformation scheme.

**Review by aryx — APPROVED** [review]
