### PR TITLE
generic mode: Allow short text targets without 2D layout

### LINKED ISSUE #6071: Issues when scanning long lines with `generic` mode
**Describe the bug**

* when you run a generic rule, this one specifically https://semgrep.dev/s/7PnQ on a one line snippet of code - it is not working
when you add extra line to a snippet, like here: https://semgrep.dev/s/E6zN - it works
same for the CLI
also if you make first line even longer https://semgrep.dev/playground/s/7PQ2 - it is not working again (with 1 extra line)
but if I add one more extra line https://semgrep.dev/s/Le26 - it works again

* it seems like this behavior also affects the `autofix` feature since it works incorrectly on such lines (but can be not related :v:)
running https://semgrep.dev/s/7PnQ in the CLI will incorrectly fix last finding

**To Reproduce**
https://semgrep.dev/s/7PnQ

### PR DESCRIPTION
**Pull request by mjambon**
Closes https://github.com/returntocorp/semgrep/issues/6071

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

**Review by aryx — APPROVED** [review]

**Comment by aryx** [comment]
not sure what's going on with the CI failure

File: changelog.d/gh-6071.changed [hunk 1]
```diff
@@ -0,0 +1,6 @@
+generic mode: allow text input without human-readable indentation up to 500
```
Comment (IagoAbal) [inline changelog.d/gh-6071.changed:1]: Can't we handle more than 500 bytes without problems? If we don't raise it then I think we should make it configurable.

Comment (mjambon) [reply changelog.d/gh-6071.changed:1]: No, minified or binary code can be extremely slow to handle, so we skip such files. Allowing single-line files up to 500 bytes is a quick fix to prevent a common problem that rule authors run into. The generic mode is for source code, i.e. human-readable text with meaningful indentation.

Removing this and other limits completely can be done with the `--force` option of `spacegrep` to developers who have access to it.
