### PR TITLE
In Spacegrep (generic mode), prefer the longest match for patterns that end with an ellipsis.

### LINKED ISSUE #10039: Generic mode (spacegrep) match for `a ...` (trailing ellipsis) is shorter than expected
**Describe the bug**

In generic mode, the ellipsis is normally lazy i.e. it will match the shortest possible sequence. An exception is when the elllipsis is placed at the end of the pattern, in which case the user wants the ellipsis to extend as far as possible since otherwise there wouldn't be a point in using a trailing ellipsis.

**To Reproduce**

https://semgrep.dev/playground/s/yyRrr

I already added a pair of tests to the internal test suite, see https://github.com/semgrep/semgrep/pull/10038

**Expected behavior**

`a ...` should match `a a b`, not just `a b`. See https://github.com/semgrep/semgrep/pull/10038 for details.

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

**Environment**

any

**Use case**

?

### PR DESCRIPTION
**Pull request by mjambon**
Fixes #10039.

This fixes how we prune overlapping patterns after the main matching step.

### CODE REVIEW

**Comment by IagoAbal** [comment]
check-semgrep-pro fails
> File "src/experiments/stubbing/Test_stubber.ml", line 19, characters 31-43:
> 19 |   t !!test_dir ~checked_output:Testo.Stdout (fun () ->
>                                     ^^^^^^^^^^^^
> Error: Unbound constructor Testo.Stdout

I guess it's due to some recent change to Testo that requires a PR to Pro?

File: changelog.d/gh-10039.fixed [hunk 1]
```diff
@@ -0,0 +1,5 @@
+In generic mode (default, spacegrep engine), matching a pattern that
+ends with an ellipsis now favors the longest match rather than the shortest
+match when multiple matches are possible. For example, for a given target
+program `a a b`, the pattern `a ... b` will match `a b` as before but
+the pattern `a ...` will now match the longer `a a b` rather than `a b`.
```
Comment (IagoAbal) [inline changelog.d/gh-10039.fixed:5]: Shouldn't it match _both_ `a`s like Semgrep would do? I know that in Spacegrep `...` only produces the shortest match, but in this case `a ...` can be matched _starting_ at two different locations, shouldn't we match both?

File: libs/spacegrep/src/test/Matcher.ml [hunk 2]
```diff
@@ -202,25 +202,17 @@ let matcher_corpus =
       Matches [ "1 2"; "2 3" ],
       "$A ... $B",
       "1 2 3" );
-    (* See also "overlapping matches with open end" *)
     ( "overlapping matches with closed end",
       Matches [ "a b" ],
       "a ... b",
       "a a b" );
+    ("overlapping matches with open end", Matches [ "a a b" ], "a ...", "a a b");
     ("leading dots", Matches [ "a b" ], "... b", "a b c");
```
Comment (IagoAbal) [inline libs/spacegrep/src/test/Matcher.ml:210]: Given "a ... b" and "a b a b" I would also expect that it either matches all of it ("a b a b") or maybe better that it produces two matches, both "a b".

File: changelog.d/gh-10039.fixed (hunk 1 above)
Comment (IagoAbal) [reply changelog.d/gh-10039.fixed:5]: So if I understand correctly, we are getting both matches "a a b" and "a b" and we're keeping the shortest one only because w don't have two matches ending at the same location. Why do we have this restriction? I need to check in the docs but it would be good to document and explain the reasoning behind it.

Comment (mjambon) [reply changelog.d/gh-10039.fixed:5]: > Shouldn't it match both as like Semgrep would do? I know that in Spacegrep `...` only produces the shortest match, but in this case `a ...` can be matched starting at two different locations, shouldn't we match both?

Do you have a use case in mind? The goal has been to minimize overlaps and redundancies.

Comment (mjambon) [reply changelog.d/gh-10039.fixed:5]: > So if I understand correctly, we are getting both matches "a a b" and "a b" and we're keeping the shortest one only because w don't have two matches ending at the same location.

Not sure what you mean by "only because we don't have two matches ending at the same location". We always prefer the shortest match when a true ellipsis is involved (not a leading or trailing ellipsis).

File: libs/spacegrep/src/test/Matcher.ml (hunk 2 above)
Comment (mjambon) [reply libs/spacegrep/src/test/Matcher.ml:210]: It would produce two matches, both "a b".
image

Comment (mjambon) [reply libs/spacegrep/src/test/Matcher.ml:210]:
```
$ ./bin/spacegrep 'a ... b' <(echo 'a b a b')
/dev/fd/63:a b a b

/dev/fd/63:a b a b
```

**Comment by mjambon** [comment]
I'm merging this because it was about fixing a particular bug. For documentation or other fixes, please file an issue.

Edit: I don't have the permission to force-merge. I need an approval.

**Review by IagoAbal — APPROVED** [review]
Please take a look at the check-semgrep-pro failure in case you haven't already because, even if unrelated to this PR, it seems related to `testo` so likely a change you made.
