### PR TITLE
accept patterns with standalone decorators (Python)

### LINKED ISSUE #4722: Python decorators cannot be matched in isolation
### Describe the bug
The pattern syntax does not allow matching a Python pattern in isolation, and requires it to be specified along with a function or method.

### To Reproduce
Demo of error: https://semgrep.dev/s/JgRj

Or more simply, any pattern like `@patch(...)` is not permitted.

### Expected behavior
I would expect it to be possible to match decorators as isolated pattern expressions.

### What is the priority of the bug to you?

- [ ] P0: blocking your adoption of Semgrep or workflow
- [x] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

### Environment
`pip install semgrep==0.82.0` on Ubuntu Linux 20.04.

### Use case
Same as https://github.com/returntocorp/semgrep/issues/4721 -- this was an alternative approach that would have avoided the inadvertent removal of any additional decorators, along with the whitespace issues of <https://github.com/returntocorp/semgrep/issues/3070>.

### PR DESCRIPTION
**Pull request by yosefAlsuhaibani**
closes https://github.com/returntocorp/semgrep/issues/4722

Modified python parsing & matching to accept patterns of the form `@deco(...)` to match code of the form 
```python
#ERROR:
@deco("rate")
def fun():
  return None
```

### previously: 

Python patterns involving decorators couldn't be expressed via `@$NAME(...)`; the parser required the decorator to be paired up with a function or class declaration such as:

```python
@$NAME(...)
def func():
  ...

# or 

@$NAME(...)
class room:
  ...
```

### Test plan:

I've written tests that test this capability in `tests/patterns/python/standalone_decorator.{py,sgrep}`, which I've used to test if this works as well as using all of the other tests in `test/*` via `make test`
PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

### CODE REVIEW

File: languages/python/ast/AST_python.ml [hunk 1]
```diff
@@ -387,6 +387,10 @@ type stmt =
   (* should be allowed just at the toplevel *)
   | FunctionDef of function_definition
   | ClassDef of class_definition
+  | Decorators of decorator list
+(* Allowed only in Semgrep; as we want to allow patterns like @$NAME()
+ * in a Semgrep pattern. Not valid Python
+ *)
```
Comment (emjin) [inline languages/python/ast/AST_python.ml]: We generally put the comment before the code (see Exec above)

File: languages/python/generic/Python_to_generic.ml [hunk 2]
```diff
@@ -590,6 +590,10 @@ and stmt_aux env x =
         }
       in
       [ G.DefStmt (ent, G.ClassDef def) |> G.s ]
+  | Decorators ld ->
+      let env = { env with context = InPattern } in
+      let ld = list (fun dec -> G.At (decorator env dec)) ld in
+      [ G.OtherStmt (G.OS_LoneAttrs, ld) |> G.s ]
```
Comment (emjin) [inline languages/python/generic/Python_to_generic.ml]: Subtlety with patterns: we'd rather parse this to a `G.Any (G.Attribute (...))` if possible, or something similar. It doesn't need to be in a statement list, the only time we'll ever want to parse this is if it's a standalone pattern*. 

See `Ruby_to_generic.any` for an example of how we've done similar modifications in the past

*If I'm wrong it won't be hard to change back

File: libs/ast_generic/AST_generic.ml [hunk 3]
```diff
@@ -1332,7 +1332,8 @@ and other_stmt_operator =
   | OS_ThrowFrom
   | OS_ThrowNothing
   | OS_ThrowArgsLocation
-    (* Python2: `raise expr, expr` and `raise expr, expr, exr` *)
+    (* Python-semgrep: allow decorators without function decls *)
+  | OS_LoneAttrs (* Python2: `raise expr, expr` and `raise expr, expr, exr` *)
```
Comment (emjin) [inline libs/ast_generic/AST_generic.ml]: Let's avoid having to add this if possible

File: tests/patterns/python/standalone_decorator.py [hunk 4]
```diff
@@ -0,0 +1,16 @@
...
+  return 42
+
+#ERROR:
+@decorator(1,2,3)
+def grumble():
+  return "wahoo"
+
+#ERROR:
+@decorator("oh")
+@decorator("my")
```
Comment (emjin) [inline tests/patterns/python/standalone_decorator.py:14]: Hm, I think I'd expect line 13 to match as well as a user. I believe my proposed change to `G.Any (G.At (...))` will do precisely that because it'll try to match both `G.At (...)` nodes, instead of just capturing the list.

Because we ran into this, can you include another test case with `@$NAME($X)`? Let's also include for each set of tests at least one example that shouldn't match.

**Review by emjin — CHANGES_REQUESTED** [review]
Great work! With patterns that match partial constructs like this, we sometimes take a different approach. Let me know if you have any questions after reading the comments

File: languages/python/generic/Python_to_generic.ml (hunk 2 above)
Comment (yosefAlsuhaibani) [reply languages/python/generic/Python_to_generic.ml]: would a sequence of decorators not be allowed? so something like:
```
$NAME($X)
$deco("hello")
```

File: tests/patterns/python/standalone_decorator.py (hunk 4 above)
Comment (yosefAlsuhaibani) [reply tests/patterns/python/standalone_decorator.py:14]: I've added additional tests to catch what you've described, and indeed it does miss those findings, which is troublesome! I've extended the old tests in `tests/patterns/python/standalone_decorator.{py,sgrep}`, and added a new set of tests for `@$NAME($X)` in `tests/patterns/python/standalone_decorator-named.{py,sgrep}`

Comment (yosefAlsuhaibani) [reply tests/patterns/python/standalone_decorator.py:14]: Also: now we do parse lone decorators in `semgrep` patterns as `any`!

File: libs/ast_generic/AST_generic.ml [hunk 5]
```diff
@@ -1332,7 +1332,7 @@ and other_stmt_operator =
   | OS_ThrowFrom
   | OS_ThrowNothing
   | OS_ThrowArgsLocation
-    (* Python2: `raise expr, expr` and `raise expr, expr, exr` *)
+  (* Python2: `raise expr, expr` and `raise expr, expr, exr` *)
```
Comment (emjin) [inline libs/ast_generic/AST_generic.ml]: I'm guessing this comment isn't meant to be there?

**Review by emjin — APPROVED** [review]
Awesome work! Be sure to add a changelog entry before merging

File: tests/patterns/python/standalone_decorator_named.py
Comment (emjin) [inline tests/patterns/python/standalone_decorator_named.py:1]: nit: I wouldn't call this "named", maybe "single_arg"

File: libs/ast_generic/AST_generic.ml (hunk 5 above)
Comment (yosefAlsuhaibani) [reply libs/ast_generic/AST_generic.ml]: I think its miss aligned; should be above `OS_ThrowFrom`?

Comment (yosefAlsuhaibani) [reply libs/ast_generic/AST_generic.ml]: Wait nvm 😭 I think I mistakingly added it

File: changelog.d/gh-4722.added
Comment (emjin) [inline changelog.d/gh-4722.added:1]: It's helpful to give a quick example of a pattern you could write

Comment (yosefAlsuhaibani) [reply changelog.d/gh-4722.added:1]: Added!

File: changelog.d/gh-4722.added [hunk 6]
```diff
@@ -0,0 +1,8 @@
+Added lone decorators as a valid Python semgrep pattern, so for example `$NAME($X)` will
```
Comment (IagoAbal) [inline changelog.d/gh-4722.added:1]: Typo here, it should have been `@$NAME($X)` I guess.

Comment (IagoAbal) [reply changelog.d/gh-4722.added:1]: Nice changelog entry BTW! To the point, and pretty easy to understand for anybody as it should be.
