### PR TITLE
Resolve imported classes inside IdQualified

### LINKED ISSUE #6001: Instance method of internal class can not be matched
**To Reproduce**
https://semgrep.dev/s/x5by

**What is the priority of the bug to you?**

- [ ] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [x] P2: regular bug that should get fixed

### PR DESCRIPTION
**Pull request by emjin**
Closes https://github.com/returntocorp/semgrep/issues/6001

Test plan: make test

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

File: semgrep-core/src/naming/Naming_AST.ml [hunk 1]
```diff
@@ -682,17 +682,25 @@ let resolve lang prog =
...
                   | Some { entname = ImportedModule (DottedName xs), _sidm; _ }
                     ->
+                      (* this is quite specific to OCaml *)
                       (* The entity is fully qualified, no need for sid *)
                       let sid = 0 in
                       let resolved =
                         untyped_ent (ImportedEntity (xs @ [ id ]), sid)
                       in
                       set_resolved env id_info resolved
+                  | Some { entname = ImportedEntity xs, _sid; _ } ->
```
Comment (aryx) [inline semgrep-core/src/naming/Naming_AST.ml]: you could factorize with the OCaml case:
```
(* this is for OCaml  *)
| Some { entname = ImportedModule (DottedName xs), _sidm; _ }
(* This was added for Java *)
| Some { entname = ImportedEntity xs, _sid; _ } ->
```

**Review by aryx — APPROVED** [review]

File: changelog.d/gh-6001.fixed [hunk 2]
```diff
@@ -0,0 +1 @@
+Resolve imported types for typed metavariables
```
Comment (IagoAbal) [inline changelog.d/gh-6001.fixed]: I think this changelog entry would be a bit cryptic for anybody (even from PA) not involved in fixing this issue.
