### PR TITLE
Fix the macOS build scripts to properly statically link libpcre.

### LINKED ISSUE #6026: semgrep-core linked to homebrew libpcre.1.dylib
**Describe the bug**
Running `semgrep` complains about `libpcre.1.dylib` not loaded. Looks to be same issue as #2624, but for macOS.

**To Reproduce**
```sh
# Install
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install semgrep

# Run
$ ./.venv/lib/python3.10/site-packages/semgrep/bin/semgrep-core
dyld[24562]: Library not loaded: /opt/homebrew/opt/pcre/lib/libpcre.1.dylib
  Referenced from: /private/tmp/test/.venv/lib/python3.10/site-packages/semgrep/bin/semgrep-core
  Reason: tried: '/opt/homebrew/opt/pcre/lib/libpcre.1.dylib' (no such file), '/usr/local/lib/libpcre.1.dylib' (no such file), '/usr/lib/libpcre.1.dylib' (no such file)

# Verify shared libraries
$ otool -L ./.venv/lib/python3.10/site-packages/semgrep/bin/semgrep-core
./.venv/lib/python3.10/site-packages/semgrep/bin/semgrep-core:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/opt/homebrew/opt/pcre/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.13.0)
```

**What is the priority of the bug to you?**

- [x] P0: blocking your adoption of Semgrep or workflow
- [ ] P1: important to fix or quite annoying
- [ ] P2: regular bug that should get fixed

**Environment**
* Apple M2
* macOS Monterey

### PR DESCRIPTION
**Pull request by sww**
Run `make setup` after removing the `libpcre` file so that semgrep-core statically links `libpcre` in the macOS build scripts. This should fix  https://github.com/returntocorp/semgrep/issues/6026.

I've also switched to using `brew --prefix` to get the correct directory prefix for `pcre`. This is relevant because depending on your Mac's CPU type, the [directory for things install by Homebrew will be different](https://docs.brew.sh/Installation):

> This script installs Homebrew to its preferred prefix (/usr/local for macOS Intel, /opt/homebrew for Apple Silicon and /home/linuxbrew/.linuxbrew for Linux)...

To confirm after building semgrep-core, otool reports it's no longer linking to `libpcre.1.dylib`:
```
$ otool -L artifacts/semgrep-core
artifacts/semgrep-core:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
```

PR checklist:

- [x] Purpose of the code is [evident to future readers](https://semgrep.dev/docs/contributing/contributing-code/#explaining-code)
- [x] Tests included or PR comment includes a reproducible test plan
- [x] Documentation is up-to-date
- [x] A changelog entry was [added to changelog.d](https://semgrep.dev/docs/contributing/contributing-code/#adding-a-changelog-entry) for any user-facing change
- [x] Change has no security implications (otherwise, ping security team)

If you're unsure on any of this, please see:

- [Contribution guidelines](https://semgrep.dev/docs/contributing/contributing-code)!
- [One of the more specific guides located here](https://semgrep.dev/docs/contributing/contributing/)

### CODE REVIEW

File: scripts/osx-m1-release.sh [hunk 1]
```diff
@@ -28,12 +28,12 @@ eval "$(opam env)"
...
 export HOMEBREW_SYSTEM=1
 
-make setup
-
 # Remove pcre dynamically linked to force MacOS to use static
 # This needs to be done before make setup since it is used there
-ls -l /usr/local/opt/pcre/lib || true
-rm -f /usr/local/opt/pcre/lib/libpcre.1.dylib
+ls -l $(brew --prefix)/opt/pcre/lib || true
+rm -f $(brew --prefix)/opt/pcre/lib/libpcre.1.dylib
```
Comment (lundberg) [inline scripts/osx-m1-release.sh]:
```suggestion
ls -l "$(brew --prefix)"/opt/pcre/lib || true
rm -f "$(brew --prefix)"/opt/pcre/lib/libpcre.1.dylib
```

File: scripts/osx-release.sh [hunk 2]
```diff
@@ -18,12 +18,12 @@ git submodule update --init --recursive --depth 1
...
 eval "$(opam env)"
 
-make setup
-
 # Remove pcre dynamically linked to force MacOS to use static
 # This needs to be done before make setup since it is used there
-ls -l /usr/local/opt/pcre/lib || true
-rm -f /usr/local/opt/pcre/lib/libpcre.1.dylib
+ls -l $(brew --prefix)/opt/pcre/lib || true
+rm -f $(brew --prefix)/opt/pcre/lib/libpcre.1.dylib
```
Comment (lundberg) [inline scripts/osx-release.sh]:
```suggestion
ls -l "$(brew --prefix)"/opt/pcre/lib || true
rm -f "$(brew --prefix)"/opt/pcre/lib/libpcre.1.dylib
```

**Review by lundberg — COMMENTED** [review]
Looks like `shellcheck` suggests quoting the command substitution.

File: scripts/osx-m1-release.sh [hunk 3]
```diff
@@ -28,12 +28,12 @@ eval "$(opam env)"
...
-make setup
-
 # Remove pcre dynamically linked to force MacOS to use static
 # This needs to be done before make setup since it is used there
-ls -l /usr/local/opt/pcre/lib || true
-rm -f /usr/local/opt/pcre/lib/libpcre.1.dylib
+ls -l "$(brew --prefix)"/opt/pcre/lib || true
+rm -f "$(brew --prefix)"/opt/pcre/lib/libpcre.1.dylib
+
+make setup
```
Comment (aryx) [inline scripts/osx-m1-release.sh:36]: I don't understand why doing make setup before or after has any effect on the compilation.
The compilation part is done by make build-core below; the only thing make setup does
is to install opam packages mostly.

Comment (aryx) [reply scripts/osx-m1-release.sh:36]: @lundberg @sww do you know why?

Comment (lundberg) [reply scripts/osx-m1-release.sh:36]: Sorry, no ... I'm not familiar with this build script and haven't investigated ... just stumbled on the problem and opened the issue.

**Review by aryx — APPROVED** [review]
weird, I don't understand why doing it after should have any impact, but
if it works ...

**Comment by sww** [comment]
I just followed what the comments when removing the libpcre files 😛.

Otherwise, I'm not sure where the `pcre` dependency comes from. I do have the OCaml `pcre` library installed as a dependency when I do `opam list`...
